version: '3'

services:
  database-mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0

    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'sample'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: UTC

    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d #설정 파일 위치

    ports:
      - '3306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'